### PR TITLE
Fix text wrapping and truncating

### LINKED ISSUE #16: Make focus entry names overflow with `...`  for long names
If the origin panel is smaller than node names it breaks into two rows in a weird way, we should add `...` overflow to cut the long name instead of breaking it into a new row
image

### PR DESCRIPTION
**Pull request by ylvaselling**
Closes #16

### CODE REVIEW

File: src/panels/OriginPanel/FocusEntry.tsx [hunk 1]
```diff
@@ -32,14 +32,14 @@ export function FocusEntry({
   }
 
   return (
-    <Group justify={'space-between'} gap={'xs'}>
+    <Group justify={'space-between'} gap={'xs'} w={'100%'}>
       <Button
         onClick={onSelectEntry}
         justify={'left'}
-        style={{ flexGrow: 1 }}
+        flex={'1 1'}
```
Comment (engbergandreas) [inline src/panels/OriginPanel/FocusEntry.tsx:39]:
```suggestion
        flex={1}
```

**Comment by engbergandreas** [comment]
insane how easy it is with Mantine, I tried sooooo many solutions that did not work 🤦‍♂️

**Review by WeirdRubberDuck — APPROVED** [review]
